version: 2
jobs:
    setup:
        docker:
            - image: continuumio/miniconda3 
        steps:
            - checkout                      # checkout the code
            - run: 
                name: Create conda environments
                command: |
                    conda env create -f environment.yml
            - run: 
                name: Install and run examples
                command: |
                    source activate rcd-env
                    pip install .
                    cd ./examples
                    rc_driver.py --help
                    rc_driver.py -i input.dat -o output.dat -c configfile.txt
workflows:
    version: 2
    build-all:
        jobs:
            - setup
