version: 2
jobs:
    setup:
        docker:
            - image: circleci/buildpack-deps:18.04
        steps:
            - checkout                      # checkout the code
            - run: 
                name: build
                name: Create conda environments
                command: |
                    echo 'export CONDA=$HOME/miniconda' >> $BASH_ENV
                    echo 'export PATH=$CONDA/bin:$PATH' >> $BASH_ENV
                    source $BASH_ENV
                    cd install
                    ./install.sh
                    ./rcd-env.sh
workflows:
    version: 2
    build-all:
        jobs:
            - setup
